apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: alb
  namespace: develop-frontend
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: ingress.k8s.aws/alb